# Generated by Django 6.1.1 on 2026-09-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDim',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('comment_content', models.TextField(blank=True, null=True)),
                ('vote', models.BigIntegerField(blank=True, null=True)),
                ('commented_on', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment_dim',
                'db_table_comment': 'comment dimension, it will have tree structure.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationDim',
            fields=[
                ('conversation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.TimeField(blank=True, null=True)),
                ('active_flag', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conversation_dim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationUser',
            fields=[
                ('conversation_user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('active_flag', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conversation_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('login_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('browser_finger_print', models.TextField(blank=True, null=True)),
                ('login_ts', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'login_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MessagesDim',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('sent_on', models.TimeField(blank=True, null=True)),
                ('active_flag', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messages_dim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostDim',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('up_vote', models.BigIntegerField(blank=True, null=True)),
                ('down_vote', models.BigIntegerField(blank=True, null=True)),
                ('comment_no', models.BigIntegerField(blank=True, null=True)),
                ('posted_on', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post_dim',
                'db_table_comment': 'keep all the post here.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('post_vote_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vote', models.SmallIntegerField(blank=True, null=True)),
                ('updated_ts', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post_vote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubboatDim',
            fields=[
                ('subboat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('subboat_name', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_pic', models.BinaryField(blank=True, null=True)),
                ('cover_pic', models.BinaryField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('update_ts', models.TimeField(blank=True, null=True)),
                ('created_ts', models.TimeField(blank=True, null=True)),
                ('active_flag', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subboat_dim',
                'db_table_comment': 'A group page for people to connect and post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubboatJoin',
            fields=[
                ('subboat_join_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_subboat_type', models.CharField(blank=True, max_length=20, null=True)),
                ('joined_at', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subboat_join',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('middle_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('created_ts', models.TimeField(blank=True, null=True)),
                ('updated_ts', models.TimeField(blank=True, null=True)),
                ('active_flag', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_details',
                'db_table_comment': 'details of users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDim',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField(unique=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_pic', models.BinaryField(blank=True, null=True)),
                ('cover_pic', models.BinaryField(blank=True, null=True)),
                ('created_ts', models.DateTimeField(blank=True, null=True)),
                ('updated_ts', models.DateTimeField(blank=True, null=True)),
                ('active_flag', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_dim',
                'db_table_comment': 'user dimension table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPassword',
            fields=[
                ('password_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password_hash', models.TextField()),
                ('salt', models.TextField(blank=True, null=True)),
                ('created_ts', models.TimeField(blank=True, null=True)),
                ('update_ts', models.TimeField(blank=True, null=True)),
                ('active_flag', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_password',
                'db_table_comment': 'keep your password secure',
                'managed': False,
            },
        ),
    ]
