# Generated by Django 6.1.1 on 2026-09-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('middle_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('created_ts', models.TimeField(blank=True, null=True)),
                ('updated_ts', models.TimeField(blank=True, null=True)),
                ('active_flag', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_details',
                'db_table_comment': 'details of users',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
